### PR TITLE
fix dependencies

### PR DESCRIPTION
**Pull request by Jonahss**
Don't need sample-apps. But ios-test-app is a dependency not a dev dependency, since instruments needs an actual app to launch with.

### CODE REVIEW

**Comment by sebv** [comment]
Client should provide the app wen needed, there should not be unnecessary production deps.

**Comment by Jonahss** [comment]
Mm. its just that the method just needs to quickly boot a sim and close it. you have to pass some dummy app to instruments just to get it to start. the user cannot be expected to supply this app because you can use this function without any app at all.

It's just the simplest dummy app, so that instruments will start a valid session and then close.

**Comment by sebv** [comment]
The app and scripts should be part of the simulator package if the simulator needs it, just pass then to the quickLaunch command. I'll figure a way to refactor it better later, we should be able to use the main instrument class for that.

**Comment by Jonahss** [comment]
Mm gotcha

**Pull request merged**
