### PR TITLE
Remove redundant quote marks for processArguments

### PR DESCRIPTION
**Pull request by camillake**

### CODE REVIEW

**Comment by camillake** [comment]
modify arguments format sent to instrument.
processArugment format example: '-e flag1 value1 -e flag2 value2'

**Comment by camillake** [comment]
Hey @jlipps ,
Could you please review this?

**Comment by jlipps** [comment]
@camillake I thought processArgument was already supposed to be an array: so you'd send in `["-e", "flag1", "value1", ...]`? or did that not work?

**Comment by camillake** [comment]
@jlipps 
Sending array or string didn't work because they are not handled. Just quotes mark added causing instrument could not recognize those parameters.
Please refer the following link for details.
https://github.com/appium/appium/issues/5909

**Comment by jlipps** [comment]
sounds like we really need to rethink this since quotes are required for the value. i'd propose something that looks like this in terms of capabilities:

```js
{"processArguments": {"flag1": "value1", "flag2": "value2"}}
```

Then Appium will be able to know what the flags and values are and turn them into something like this:

```
for (let [flag, value] of _.pairs(this.processArguments)) {
  args = args.concat(flag, JSON.stringify(value));
}
```

which should do the right thing.

What do you think about that @camillake ?

**Comment by camillake** [comment]
@jlipps 
Thanks for your suggest.
I think you miss '-e' which is must to have for instruments.
```python
for (let [flag, value] of _.pairs(this.processArguments)) {
  args = args.concat(['-e', flag, JSON.stringify(value)]);
}
```
If there is no more problem, I will update again.
More, there is check failure. I would like to know how to do completed tests for update. 
Would you please provide test steps or commands for update verification to sub projects under Appium?

**Comment by jlipps** [comment]
@camillake ah yes i did need '-e'. thanks.

So in order to test this I think we need two things:

1) some unit tests that test that assuming we have the right data in this.processArguments, that it gets made into command line arguments correctly

2) we probably need to update our test application to respond to command line flags so that we can change some label on the application and assert that this way of doing things is working. does that make sense? if you're not comfortable adding that to our test app we can get someone to help

**Comment by camillake** [comment]
@jlipps 
I agree with you and would like to do unit test for that change.

**Comment by imurchie** [comment]
Just bringing in the discussion from the issue related to this: https://github.com/appium/appium-instruments/issues/43

**Comment by GreenJeans** [comment]
Is there any progress on this?  Using Appium 1.4.13, I am unable to pass environment variables using processArguments capability.

    DesiredCapabilities capabilities = new DesiredCapabilities();
    String arguments = "-e debugController YES";
    capabilities.setCapability("processArguments", arguments);

Results in the Appium console log containing 

    info: [debug] Spawning instruments with command: ... "-e debugController YES"

instead of

    -e debugController "YES"

**Comment by imurchie** [comment]
This was implemented elsewhere. It is not available on 1.4.13. It _is_ in 1.5.2.

**Pull request closed without merging**
