### PR TITLE
change the regexp to include ios 10 version

### PR DESCRIPTION
**Pull request by bigfei**
for ios >10, 2 digits version number is needed for regexp.

### CODE REVIEW

**Comment by bigfei** [comment]
@jlipps please merge this for ios 10

**Comment by imurchie** [comment]
But Instruments does not work for iOS 10/Xcode 8, so there is no need for this, is there?

**Comment by bigfei** [comment]
Yeep, it doesn't need for iOS 10. 
Now I am doing a side project that needs to list the current available  devices and put them in the UI. The  `getAvailableDevices` function inside the `instruments.utils` module does give me a hint. Maybe appium itself doesn't need to fix it anymore, but some other nodejs project might need it. 
Anyway O(∩_∩)O thx.

**Comment by jlipps** [comment]
@bigfei I'm OK including this, however it looks like some tests failed in travis.

**Comment by jlipps** [comment]
And they seem relevant to your change; can you investigate?

**Comment by jlipps** [comment]
published in `appium-instruments@3.8.6`

**Pull request merged**
